language: generic
sudo: required
services: docker

matrix:
  include:
    # https://hub.docker.com/_/fedora/
    - env: CONTAINER_IMAGE=fedora:rawhide TOXENV=py36
    - env: CONTAINER_IMAGE=fedora:28 TOXENV=py36
    # https://hub.docker.com/_/centos/
    - env: CONTAINER_IMAGE=centos:7 TOXENV=py27
  allow_failures:
    - env: CONTAINER_IMAGE=fedora:rawhide TOXENV=py36
    - env: CONTAINER_IMAGE=fedora:28 TOXENV=py36

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh
