language: python
sudo: required
services: docker

matrix:
  include:
    # https://hub.docker.com/_/fedora/
    # will use centos:8 after it released
    - env: CONTAINER_IMAGE=fedora:28 TOXENV=py36

install:
  - pip install coveralls
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - sed -i -e s@/build@"$(pwd)"@g .coverage
  - coveralls
